let presets;

function establishPresets(){
    presets = {
        "Soothing Pluck": {
            name: 'Soothing Pluck',
            chorusFreq: 10,
            chorusDelay: 0,
            chorusFeedback: 0,
            Velocity: 0.17,
            Distortion: 0,
            pingpongDelay: 0,
            pingpongFeedback: 0,
            vibratoDepth: 0,
            vibratoFreq: 0,
            filterCutoff: 6740,
            filterType: 'lowpass',
            waveType: 'sine',
            octave: 4,
            envAttack: 0,
            envDecay: 0.3,
            envSustain: 0.3,
            envRelease: .02,
            reverbDecay: 1.06,
            reverbDryWet: 0.49,
            portamento: 0,
            delayTime: 0,
            delayFeedback: 0,
            // delayDryWet: 0
        },
    
        "Ringing": {
            name: 'Ringing',
            chorusFreq: 30,
            chorusDelay: 88,
            chorusFeedback: .9,
            Velocity: .15,
            Distortion: 0,
            pingpongDelay: 0,
            pingpongFeedback: 0,
            vibratoDepth: 0,
            vibratoFreq: 0,
            filterCutoff: 9000,
            filterType: 'lowpass',
            waveType: 'triangle',
            octave: 5,
            envAttack: 0,
            envDecay: 0.3,
            envSustain: 0.22,
            envRelease: 0.16,
            reverbDecay: 0.5,
            reverbDryWet: 0.33,
            portamento: 0,
            delayTime: 0,
            delayFeedback: 0
        },

        "Vibing": {
            name: 'Vibing',
            chorusFreq: 0,
            chorusDelay: 0,
            chorusFeedback: 0,
            Velocity: .11,
            Distortion: 0,
            pingpongDelay: 0,
            pingpongFeedback: 0,
            vibratoDepth: .21,
            vibratoFreq: 11.85,
            filterCutoff: 6300,
            filterType: 'lowpass',
            waveType: 'sawtooth',
            octave: 4,
            envAttack: 0.53,
            envDecay: 0.3,
            envSustain: 0.56,
            envRelease: 0.76,
            reverbDecay: 0.5,
            reverbDryWet: 0.33,
            portamento: 0,
            delayTime: 0,
            delayFeedback: 0
        },

        "Warm Waves": {
            name: 'Warm Waves',
            chorusFreq: 0,
            chorusDelay: 0,
            chorusFeedback: .77,
            Velocity: .16,
            Distortion: 0,
            pingpongDelay: 0,
            pingpongFeedback: 0,
            vibratoDepth: .08,
            vibratoFreq: 0.56,
            filterCutoff: 3667,
            filterType: 'lowpass',
            waveType: 'sawtooth',
            octave: 3,
            envAttack: 1.3,
            envDecay: 0.85,
            envSustain: 0.58,
            envRelease: 1.35,
            reverbDecay: 1.11,
            reverbDryWet: 0.53,
            portamento: 0,
            delayTime: 0,
            delayFeedback: 0
        },

        "Gameboy": {
            name: 'Gameboy',
            chorusFreq: 0,
            chorusDelay: 0,
            chorusFeedback: 0,
            Velocity: .12,
            Distortion: 0,
            pingpongDelay: 0,
            pingpongFeedback: 0,
            vibratoDepth: .04,
            vibratoFreq: 11.11,
            filterCutoff: 1222,
            filterType: 'highpass',
            waveType: 'square',
            octave: 4,
            envAttack: 0,
            envDecay: 0.62,
            envSustain: 0.77,
            envRelease: 0,
            reverbDecay: 0.5,
            reverbDryWet: 0.33,
            portamento: 0,
            delayTime: 0,
            delayFeedback: 0
        },

        "Cursed": {
            name: 'Cursed',
            chorusFreq: 0,
            chorusDelay: 4.07,
            chorusFeedback: 1,
            Velocity: .16,
            Distortion: 0,
            pingpongDelay: 0,
            pingpongFeedback: 0,
            vibratoDepth: .09,
            vibratoFreq: .56,
            filterCutoff: 8148,
            filterType: 'lowpass',
            waveType: 'sawtooth',
            octave: 1,
            envAttack: 2,
            envDecay: 0.85,
            envSustain: 0.58,
            envRelease: 2,
            reverbDecay: 1.11,
            reverbDryWet: 0.53,
            portamento: 0,
            delayTime: 0,
            delayFeedback: 0
        }
    }
}

establishPresets();

export { presets, establishPresets };